DWAPlannerROS:
  acc_lim_x: 0.8
  acc_lim_theta: 1.5

  max_vel_x: 0.7
  min_vel_x: 0.0
  max_vel_theta: 1.0
  min_vel_theta: 0.2

  yaw_goal_tolerance: 0.35
  xy_goal_tolerance: 0.25
  latch_xy_goal_tolerance: true

  sim_time: 2.0
  vx_samples: 12
  vtheta_samples: 20
  controller_frequency: 10.0

  path_distance_bias: 32.0
  goal_distance_bias: 20.0
  occdist_scale: 0.04

  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2
