global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  transform_tolerance: 0.5

  # No static map yet (good for Gazebo prototype)
  static_map: false
  rolling_window: true
  width: 20.0
  height: 20.0
  resolution: 0.10

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: dynamic_map_cloud
    dynamic_map_cloud:
      data_type: PointCloud2
      topic: /dynamic_map/inflated_voxel_map
      marking: true
      clearing: false
      min_obstacle_height: 0.05
      max_obstacle_height: 2.0

  inflation_layer:
    inflation_radius: 0.55
